grails-app/domain/issuetracker/Issue.groovy
package issuetracker

class Issue {
	
	int issueId
	String issue
	String issueType
	String issueDescription
	String submittedBy
	Date submittedOn
	String assignedTo
	Date assignedOn
	String issueStatus
	String priority
	String comments
	String projects
	
	
    static constraints = {
		issueType(inList: ["Functional", "Cosmetic", "Business"])
		issueStatus(inList: ["New", "Accepted", "Closed", "Not an Issue"])
		priority(inList: ["low", "medium", "high"])
		issueDescription(size: 0..5000)
		comments(size: 0..5000)
		projects(inList: ["prj1", "prj2", "prj3"])
    }
}

grails-app/controllers/issuetracker/CreateIssueController.groovy
package issuetracker

class CreateIssueController {
	
	def view = {
		render(view:"create", model: [Issue.list()]);
	}
	
    def create = { 
		redirect action: 'success', params: params
	}
	
	def success = {
		render(view:"success");
	}
}

grails-app/controllers/issuetracker/ViewIssueController.groovy
package issuetracker

class ViewIssueController {

    def view = { 
		render(view:"viewall");		
	}
}

grails-app/views/createIssue/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<%@ page import="issuetracker.Issue" %>
		
		<meta name="layout" content="main"/>
		<title>Welcome to IssueTracker</title>
		<style type="text/css" media="screen">
			#status {
				background-color: #eee;
				border: .2em solid #fff;
				margin: 2em 2em 1em;
				padding: 1em;
				width: 12em;
				float: left;
				-moz-box-shadow: 0px 0px 1.25em #ccc;
				-webkit-box-shadow: 0px 0px 1.25em #ccc;
				box-shadow: 0px 0px 1.25em #ccc;
				-moz-border-radius: 0.6em;
				-webkit-border-radius: 0.6em;
				border-radius: 0.6em;
			}

			.ie6 #status {
				display: inline; /* float double margin fix http://www.positioniseverything.net/explorer/doubled-margin.html */
			}

			#status ul {
				font-size: 0.9em;
				list-style-type: none;
				margin-bottom: 0.6em;
				padding: 0;
			}

			#status li {
				line-height: 1.3;
			}

			#status h1 {
				text-transform: uppercase;
				font-size: 1.1em;
				margin: 0 0 0.3em;
			}

			#page-body {
				margin: 2em 1em 1.25em 18em;
			}

			h2 {
				margin-top: 1em;
				margin-bottom: 0.3em;
				font-size: 1em;
			}

			p {
				line-height: 1.5;
				margin: 0.25em 0;
			}

			#controller-list ul {
				list-style-position: inside;
			}

			#controller-list li {
				line-height: 1.3;
				list-style-position: inside;
				margin: 0.25em 0;
			}

			@media screen and (max-width: 480px) {
				#status {
					display: none;
				}

				#page-body {
					margin: 0 1em 1em;
				}

				#page-body h1 {
					margin-top: 0;
				}
			}
		</style>
	</head>
	<body>
		<a href="#page-body" class="skip"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div id="status" role="complementary">
			<h1>USEFUL LINKS</h1><br>
			<ul>
				<li style="cursor: pointer;"><g:link url="/issuetracker/">Home</g:link></li>
				<li style="cursor: pointer;"><g:link controller="createIssue" action="view">Create Issue</g:link></li>
				<li style="cursor: pointer;"><g:link controller="viewIssue" action="view">View All</g:link></li>
			</ul>
		</div>
		<div id="page-body" role="main">
			<h1>Create Issue</h1><br><br>
			
			<g:form controller="createIssue" action="create">
				<table>
					<tr>
        				<td><label for="name">Issue Name:</label></td>
        				<td><g:textField name="issue" maxlength="50" value=""></g:textField></td>
        			</tr>
        			<tr>	
        				<td><label for="name">Issue Type:</label></td>
        				<td><g:select name="issueType" from="${['','Functional', 'Cosmetic', 'Business']}" ></g:select></td>
        			</tr>
        			<tr>	
        				<td><label for="name">Issue Description:</label></td>
        				<td><g:textArea name="issueDescription"></g:textArea> </td>
        			</tr>
        			<tr>	
        				<td><label for="name">Submitted By:</label></td>
        				<td><g:textField name="submittedBy" maxlength="50" value=""></g:textField></td>
        			</tr>
        			<tr>	
        				<td><label for="name">Assigned To:</label></td>
        				<td><g:textField name="assignedTo" maxlength="50" value=""></g:textField></td>
        			</tr>
        			<tr>	
        				<td><label for="name">Status:</label></td>
        				<td><g:select name="issueStatus" from="${['','New', 'Accepted', 'Closed', 'Not an Issue']}" ></g:select></td>
        			</tr>
        			<tr>	
        				<td><label for="name">Priority:</label></td>
        				<td><g:select name="priority" from="${['','low', 'medium', 'high']}" ></g:select></td>
        			</tr>
        			<tr>	
        				<td><label for="name">Comments:</label></td>
        				<td><g:textArea name="comments"></g:textArea> </td>
        			</tr>
        		</table>
    			<input value="Submit" type="submit">	
			</g:form>
		</div>
	</body>
</html>

grails-app/views/createIssue/success.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main"/>
		<title>Welcome to IssueTracker</title>
		<style type="text/css" media="screen">
			#status {
				background-color: #eee;
				border: .2em solid #fff;
				margin: 2em 2em 1em;
				padding: 1em;
				width: 12em;
				float: left;
				-moz-box-shadow: 0px 0px 1.25em #ccc;
				-webkit-box-shadow: 0px 0px 1.25em #ccc;
				box-shadow: 0px 0px 1.25em #ccc;
				-moz-border-radius: 0.6em;
				-webkit-border-radius: 0.6em;
				border-radius: 0.6em;
			}

			.ie6 #status {
				display: inline; /* float double margin fix http://www.positioniseverything.net/explorer/doubled-margin.html */
			}

			#status ul {
				font-size: 0.9em;
				list-style-type: none;
				margin-bottom: 0.6em;
				padding: 0;
			}

			#status li {
				line-height: 1.3;
			}

			#status h1 {
				text-transform: uppercase;
				font-size: 1.1em;
				margin: 0 0 0.3em;
			}

			#page-body {
				margin: 2em 1em 1.25em 18em;
			}

			h2 {
				margin-top: 1em;
				margin-bottom: 0.3em;
				font-size: 1em;
			}

			p {
				line-height: 1.5;
				margin: 0.25em 0;
			}

			#controller-list ul {
				list-style-position: inside;
			}

			#controller-list li {
				line-height: 1.3;
				list-style-position: inside;
				margin: 0.25em 0;
			}

			@media screen and (max-width: 480px) {
				#status {
					display: none;
				}

				#page-body {
					margin: 0 1em 1em;
				}

				#page-body h1 {
					margin-top: 0;
				}
			}
		</style>
	</head>
	<body style="width: 100%; height: 100%;" >
		<a href="#page-body" class="skip"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div id="status" role="complementary">
			<h1>USEFUL LINKS</h1><br>
			<ul>
				<li style="cursor: pointer;"><g:link url="/issuetracker/">Home</g:link></li>
				<li style="cursor: pointer;"><g:link controller="createIssue" action="view">Create Issue</g:link></li>
				<li style="cursor: pointer;"><g:link controller="viewIssue" action="view">View All</g:link></li>				
			</ul>
		</div>
		<div id="page-body" role="main">
			<br><br>	
			<h1>Issue Created successfully</h1>
		</div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
		<g:layoutHead/>
		<r:layoutResources />
	</head>
	<body>
		<div id="grailsLogo" role="banner">
			<h1> Issue Tracker</h1>
		</div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<g:javascript library="application"/>
		<r:layoutResources />
	</body>
</html>

grails-app/views/viewIssue/viewall.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main"/>
		<title>Welcome to IssueTracker</title>
		<script type="text/javascript">
			function showDetails(issueId) {
				alert('<<Issue details to be displayed in a jquery div dialog>>');	
			}
		</script>
		<style type="text/css" media="screen">
			#status {
				background-color: #eee;
				border: .2em solid #fff;
				margin: 2em 2em 1em;
				padding: 1em;
				width: 12em;
				float: left;
				-moz-box-shadow: 0px 0px 1.25em #ccc;
				-webkit-box-shadow: 0px 0px 1.25em #ccc;
				box-shadow: 0px 0px 1.25em #ccc;
				-moz-border-radius: 0.6em;
				-webkit-border-radius: 0.6em;
				border-radius: 0.6em;
			}

			.ie6 #status {
				display: inline; /* float double margin fix http://www.positioniseverything.net/explorer/doubled-margin.html */
			}

			#status ul {
				font-size: 0.9em;
				list-style-type: none;
				margin-bottom: 0.6em;
				padding: 0;
			}

			#status li {
				line-height: 1.3;
			}

			#status h1 {
				text-transform: uppercase;
				font-size: 1.1em;
				margin: 0 0 0.3em;
			}

			#page-body {
				margin: 2em 1em 1.25em 18em;
			}

			h2 {
				margin-top: 1em;
				margin-bottom: 0.3em;
				font-size: 1em;
			}

			p {
				line-height: 1.5;
				margin: 0.25em 0;
			}

			#controller-list ul {
				list-style-position: inside;
			}

			#controller-list li {
				line-height: 1.3;
				list-style-position: inside;
				margin: 0.25em 0;
			}

			@media screen and (max-width: 480px) {
				#status {
					display: none;
				}

				#page-body {
					margin: 0 1em 1em;
				}

				#page-body h1 {
					margin-top: 0;
				}
			}
		</style>
	</head>
	<body style="width: 100%; height: 100%;" >
		<a href="#page-body" class="skip"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div id="status" role="complementary">
			<h1>USEFUL LINKS</h1><br>
			<ul>
				<li style="cursor: pointer;"><g:link url="/issuetracker/">Home</g:link></li>
				<li style="cursor: pointer;"><g:link controller="createIssue" action="view">Create Issue</g:link></li>
				<li style="cursor: pointer;"><g:link controller="viewIssue" action="view">View All</g:link></li>				
			</ul>
		</div>
		<div id="page-body" role="main"><br><br><br><br>
			<h1>Issues</h1>
			<table>
			<tr><th>Issue Id</th><th>Issue Name</th><th>Issue Type</th><th>Submitted By</th><th>Submitted Date</th><th>Assigned To</th><th>Status</th></tr>
			<tr><td><a href="javascript: showDetails(101);">101</a></td><td>issue1</td><td>Functional</td><td>bpillari</td><td><g:formatDate format="MM-dd-yyyy" date="${new Date()}" /> </td><td>bpillari</td><td>New</td></tr>
			<tr><td><a href="javascript: showDetails(101);">102</a></td><td>issue2</td><td>Cosmetic</td><td>bpillari</td><td><g:formatDate format="MM-dd-yyyy" date="${new Date()}" /> </td><td>bpillari</td><td>Closed</td></tr>
			<tr><td><a href="javascript: showDetails(101);">103</a></td><td>issue3</td><td>Functional</td><td>bpillari</td><td><g:formatDate format="MM-dd-yyyy" date="${new Date()}" /> </td><td>bpillari</td><td>New</td></tr>
			</table>
		</div>
		<div id="dialog" title="Basic dialog" style="display: none;">
			<!-- details to be populated for the issue id -->
		</div>
	</body>
</html>